title = "Hope For Elodie"
baseURL = "/"
languageCode = "en-us"
theme = "ananke"
relativeURLs = true
canonifyURLs = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
contentDir = "content"
Paginate = 8
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  description = "A little girl"
  instagram = "https://www.instagram.com/paperbuttons/"
  background_color_class = "bg-black-30"
  featured_image = "/images/elodie_hero_crop.jpg"
  recent_posts_number = 2
